DATA_FOLDER = "data\\"
CACM_QUERIES_FILE = DATA_FOLDER + "cacm.query.txt"
CACM_PARSED_QUERIES_FILE = DATA_FOLDER + "cacm.query.parsed.txt"
CACM_DOCS_FOLDER = DATA_FOLDER + "cacm\\"
CACM_CORPUS_FOLDER = DATA_FOLDER + "cacm_corpus\\"
CACM_CORPUS_LUCENE_INDEX_FOLDER = DATA_FOLDER + "cacm_corpus_lucene_index\\"
RESULTS_BASE_FOLDER = "results\\"
TASK_1_RESULTS_FOLDER = RESULTS_BASE_FOLDER + "task_1\\"
TF_IDF_RESULTS_FOLDER = TASK_1_RESULTS_FOLDER + "TF_IDF\\"
QUERY_LM_JM_RESULTS_FOLDER = TASK_1_RESULTS_FOLDER + "QUERY_LM_JM\\"
BM25_RESULTS_FOLDER = TASK_1_RESULTS_FOLDER + "BM25\\"
LUCENE_RESULTS_FOLDER = TASK_1_RESULTS_FOLDER + "LUCENE\\"
NO_OF_SEARCH_RESULTS = 100

COMMON_WORDS_FILE = DATA_FOLDER + "common_words"
TEXT_FILE_EXTN = ".txt"
HTML_FILE_EXTN = ".html"
INVERTED_INDEX_FILE = DATA_FOLDER + "inverted_index_data.txt"
DOC_TERMS_COUNT_FILE = DATA_FOLDER + "doc_terms_count_data.txt"
PARSED_QUERIES_FILE = DATA_FOLDER + "cacm.query.parsed.txt"

# BM25 ALGORITHM CONFIG
BM25_RELEVANT_INFO = 0
BM25_R = 0
BM25_K1 = 1.2
BM25_K2 = 100
BM25_B = 0.75
BM25_QUERY_FREQ = 1

# QUERY EXPANSION CONFIG
TASK_2_RESULTS_FOLDER = RESULTS_BASE_FOLDER + "task_2\\"
ENHANCED_QUERY_BASE = TASK_2_RESULTS_FOLDER + "enhanced_queries\\"
STEM_ENHANCED = ENHANCED_QUERY_BASE + "cacm.query.stem.txt"
STEM_PRF = ENHANCED_QUERY_BASE + "cacm.query.prf.txt"
PSF_RANK_LIST = TASK_2_RESULTS_FOLDER + "pseudo_relevance-feedback\\"


# EXTRA CREDITS
ERRONEOUS_QUERIES_FILE = DATA_FOLDER + "cacm.query.error.txt"
QUERY_ERROR_RATE = 0.8
UNINDEXED_TXT_FILE = DATA_FOLDER + "unindexed_words.txt"
EXTRA_CREDITS_RESULTS_FOLDER = RESULTS_BASE_FOLDER + "extra_credits\\"
SUGGESTED_QUERIES_FILE = EXTRA_CREDITS_RESULTS_FOLDER + "cacm.query.correct.{}.txt"
NO_OF_QUERY_SUGGESTIONS = 6

# EVALUATION
RELEVANT_DOC_INFO = DATA_FOLDER + "cacm.rel.txt"

#snippet generation

SNIPPET_RESULTS = RESULTS_BASE_FOLDER + "phase_2\\"

# Query without stop words
WITHOUT_STOP_QUERIES_FILE = DATA_FOLDER + "cacm.query.parsed.withoutstop.txt"

# Stemming
STEMMED_CORPUS = DATA_FOLDER + "stemmed_corpus\\"
STEM_FILE = DATA_FOLDER + "cacm_stem.txt"
STEM_QUERY_FILE = DATA_FOLDER + "cacm_stem.query.txt"

# EVALUATION
EVALUATION_RESULTS_FOLDER = RESULTS_BASE_FOLDER + "phase_3\\"
BM25_EVALUATION  = EVALUATION_RESULTS_FOLDER + "BM25\\"
